sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

# safelist
branches:
  only:
  - master
  - ngrx

before_script:
  - npm install -g @angular/cli

script:
  - npm run test
