sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

install: travis_wait 20 mvn install  mvn -f path/to/pom.xml

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - npm run test
